### PR TITLE
(Bug) Dutch Auction crowdsale: global min cap is not disabled after crowdsale finalization

### LINKED ISSUE #998: (Bug) Dutch Auction crowdsale: global min cap is not disabled after crowdsale finalization
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Ropsten

### If you were able to create it, what is the URL of your crowdsale?

`manage/0xa20b44b81eb5c5fe363282f9a42eaebac35ff0415b44cd916e200df009a3ec7a`

### Do you have screenshots showing the problem?

Crowdsale was finalized, but `global min cap` input is still not disabled: 

screencapture-localhost-3000-manage-0xa20b44b81eb5c5fe363282f9a42eaebac35ff0415b44cd916e200df009a3ec7a-2018-06-29-17_26_46

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

No

---

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #998

- Validate not edit mincap after finish

This pull request depends on the following #1007 
This branch (issue#998) has as its origin the branch (issue#975)

See image with problem solved
issue 998-disable-button-min-cap

### CODE REVIEW

File: src/components/manage/index.js [hunk 1]
```diff
@@ -694,7 +700,7 @@ export class Manage extends Component {
           initialValues={{ ...this.initialValues }}
           component={ManageForm}
           canEditTiers={ownerCurrentUser && !canFinalize && !crowdsaleIsFinalized}
-          canEditMinCap={ownerCurrentUser && !crowdsaleHasEnded && !crowdsaleIsWhitelisted}
+          canEditMinCap={ownerCurrentUser && !crowdsaleHasEnded && !crowdsaleIsWhitelisted && !crowdsaleIsFinalized}
```
Comment (mariano-aguero) [inline src/components/manage/index.js]: Variable added to validate mincap edit
