### PR TITLE
(Fix) Add validation to decimals

### LINKED ISSUE #568: (Fix) add validation to decimals field
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Each network

### If you were able to create it, what is the URL of your crowdsale?

No

### Do you have screenshots showing the problem?

No. Users are trying to insert float values to the field. Should be validated.

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

Uncaught (in promise) Error: Error: [number-to-bn] while converting number "0.001" to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported. Given value: "0.001"
   at l (utils.js:64)
   at Object.f [as toTwosComplement] (utils.js:77)
   at o.s [as _inputFormatter] (formatters.js:44)
   at o.encode (type.js:188)
   at index.js:255
   at Array.map (<anonymous>)
   at m.encodeParameters (index.js:254)
   at microservices.js:32
   at new Promise (<anonymous>)
   at o (microservices.js:14)
   at e.getEncodedABIClientSide (microservices.js:8)
   at utils.js:38
   at <anonymous>

---

### PR DESCRIPTION
**Pull request by fernandomg**
Closes #568 

Created a new component (`NumericInput`) whose intention is to be used across all the wizard where a number is required.

I just updated the **DECIMALS** input field for `stepTwo` with this new component

### CODE REVIEW

File: src/components/Common/NumericInput.js [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+const { VALID, INVALID } = VALIDATION_TYPES
+
+@observer
+export class NumericInput extends Component {
+  constructor (props) {
+    super(props)
+
+    this.state = {
+      value: '',
+      validation: {
```
Comment (fvictorio) [inline src/components/Common/NumericInput.js]: Since `NumericInput` can only have one value, I think this can be flattened to `this.state = { value, pristine, valid}`

Comment (fernandomg) [reply src/components/Common/NumericInput.js]: done, thanks!
