### PR TITLE
(Fix) Invest multiple tiers fix

### LINKED ISSUE #907: (Bug)Minted-Multitier: 2nd tier doesn't start
Test URL : localhost with latest commit https://github.com/poanetwork/token-wizard/commit/5226634f72c9f83b9e13aff6b82ba8b336697c96

Steps:
1. Create crowdsale: 2 tiers with whitelist
2. Wait until 1st tier time is over
3. Open invest page, observe timer, try to buy

Expected result:
 - 2nd tier should start immediately after 1st

Actual result:
 - 2nd tier doesn't starting
 - contract's method ```getCurrentTierInfo ``` point to 1st tier which has ended

Exec ID : 0x8deaa38e932ee46ee91fa60c6619b1f37ede23d12ee0bf83a49bd6a7fafdee34

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropstenr*

### If you were able to create it, what is the URL of your crowdsale?

*http://localhost:3000/invest?exec-id=0x8deaa38e932ee46ee91fa60c6619b1f37ede23d12ee0bf83a49bd6a7fafdee34&networkID=3*

### Do you have screenshots showing the problem?

screen shot 2018-05-23 at 23 37 33
screen shot 2018-05-23 at 23 24 58
### Do you see errors in the dev console? If yes, please include a screenshot

*No*

---

### PR DESCRIPTION
**Pull request by vbaranov**
Closes #907 

Retrieving of tiers' amount and dates (start date and end date) is fixed for invest page

### CODE REVIEW

File: src/components/crowdsale/utils.js [hunk 1]
```diff
@@ -182,42 +182,69 @@ export let getCrowdsaleTargetDates = (initCrowdsaleContract, execID) => {
...
+
+  return {
+    startsAtMilliseconds,
+    endsAtMilliseconds
+  }
+}
+
+let fillCrowdsalePageStoreDates = (startsAtMilliseconds, endsAtMilliseconds) => {
+  if (!crowdsalePageStore.startDate || crowdsalePageStore.startDate > startsAtMilliseconds)
+    crowdsalePageStore.startDate = startsAtMilliseconds
```
Comment (fernandomg) [inline src/components/crowdsale/utils.js]: This should be set through `setProperty` method

File: src/components/crowdsale/utils.js [hunk 2]
```diff
@@ -182,42 +182,69 @@ export let getCrowdsaleTargetDates = (initCrowdsaleContract, execID) => {
...
+
+          return Promise.all(getTiersStartAndEndDates)
+        })
+        .then((tiersStartAndEndDates) => {
+          console.log("tiersStartAndEndDates:", tiersStartAndEndDates)
+          let crowdsaleStartDate
+          let crowdsaleEndDate = 0
+          tiersStartAndEndDates.forEach((tierStartAndEndDates) => {
+            const tierDates = setTierDates(tierStartAndEndDates.tier_start, tierStartAndEndDates.tier_end)
+            crowdsaleStartDate = crowdsaleStartDate ? Math.min(crowdsaleStartDate, tierDates.startsAtMilliseconds) : tierDates.startsAtMilliseconds
```
Comment (fernandomg) [inline src/components/crowdsale/utils.js]: Is it necessary to make those comparisons (`min`, `max`)?

If you're requesting tiers in order, `tiersStartAndEndDates` must be ordered as well. Thus, just picking the `tier_start` from the first tier, and `tier_end` from the last one should be enough?
