### PR TITLE
(Fix) Disable Continue button until all assets are saved to MobX storage

### LINKED ISSUE #1043: (Fix) Disable Continue button until all assets are saved to MobX storage
**Problem**: We should disable CONTINUE button at step 1 until all assets form `./public/contracts` folder will not be saved to `ContractStore`.

**Solution**: we have a billet for it
https://github.com/poanetwork/token-wizard/blob/2.0/src/components/stepOne/index.js#L9. And similar functionality is implememnted in `master` branch (https://github.com/poanetwork/token-wizard/pull/516)

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #1043 

- Add observable to check downloadStatus
- Refactoring section home and section stepOne to apply observable
- Refactoring some constants

### CODE REVIEW

File: src/components/stepOne/index.js [hunk 1]
```diff
@@ -2,20 +2,20 @@ import React from 'react'
...
 
-//todo: downloadStatus is not used
-const ContinueButton = ({ downloadStatus }) => {
-  return (
-    <Link to="/2">
-      <span className="button button_fill">Continue</span>
-    </Link>
-  )
-}
+const logger = logdown('TW:manage:utils')
```
Comment (vbaranov) [inline src/components/stepOne/index.js]: @mariano-aguero why `TW:manage:utils` ? Maybe, `TW:components:stepOne`?
