### PR TITLE
(Bug) Minted-Multitier: allow owner to finalize before end of crowdsale if all tokens were sold in latest tier

### LINKED ISSUE #1026: (Bug) Minted-Multitier: allow owner to finalize before end of crowdsale if all tokens were sold in latest tier
Scenario:  
 - MintedCapped strategy, miltitier crowdsale
 - 1st tier: not all  tokens were sold 
 -  latest tier: all tokens  were sold before time expired 

Problem: in this case owner can't finalize and has to wait  until crowdsale will be ended . But there is no reason to wait  since all tokens were sold and investors can't buy anymore.

Solution: change condition for finalization.
Now:
    - all tokens were sold  in all tiers OR latest tier's time is expired
Should be:
   - all tokens were sold in latest tier  OR latest tier's time is expired
---

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #1026

- Added new validation related to latest tier

### CODE REVIEW

File: src/components/manage/index.js [hunk 1]
```diff
@@ -526,26 +526,58 @@ export class Manage extends Component {
...
+
+        //Check if tier is finish
+        let tierDates = await getTierStartAndEndDates(...params, tierIndex).call()
+        if (tierDates && !tierDates.hasOwnProperty('tier_end')) {
+          tierDates.tier_end = tierDates[1]
+        }
+        const tierIsEnded = tierDates.tier_end * 1000 <= Date.now()
+
+        //Check if is lastTier , if lastTier is not ended, if tokens remaining is zero in last tier
+        mintedCappedWithLastTierAllSold = numOfTiers == actualTier && !tierIsEnded && tierTokensRemaining == 0
```
Comment (vbaranov) [inline src/components/manage/index.js]: @mariano-aguero It seems `!tierIsEnded` is a redundant check. Isn't it?  Because if last tier has already ended `crowdsaleHasEnded` will be `true`. I think we could remove this check and aslo remove code from the lines 563 - 568.

Comment (mariano-aguero) [reply src/components/manage/index.js]: @vbaranov changes done!
