### PR TITLE
(Fix) Countdown timer

### LINKED ISSUE #584: (Bug) Multiple-tiers crowdsale, countdown timer show time to the end of  latest tier
### Step to reproduce:
1. Create 2  tiers.
 tier1 : start 02/08/2018 11:15pm   ,   end 02/08/2018 11:45pm
 tier2 : start 02/09/2018 11:15pm   ,   end 02/09/2018 11:45pm
2. Deploy tokens 
3. Observe countdown value in the final page
Expected result: countdown should indicate time left to the start of the first tier 
Actual result: countdown indicates time left to the end  of the second tier 

Crowdsale was created 02/08/2018 around 10:00am

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Rinkeby*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.poa.network/manage/0xd0d45D5BcB4f546d06f88D93E97F24dbdA225662

### Do you have screenshots showing the problem?
Tier1
screenshoot1518112140707

Tier2
screenshoot1518112143549

cuntdownfinal
countfinal

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*No*

---

### PR DESCRIPTION
**Pull request by fernandomg**
Closes #584

Refer to: https://github.com/poanetwork/token-wizard/issues/584#issuecomment-372437791

### CODE REVIEW

File: src/components/invest/index.js [hunk 1]
```diff
@@ -116,26 +123,55 @@ export class Invest extends React.Component {
...
-          })
         })
       })
     })
   }
 
+  setTimers = () => {
+    const { crowdsalePageStore } = this.props
+    let nextTick = 0
+    let millisecondsToNextTic = 0
```
Comment (fvictorio) [inline src/components/invest/index.js]: Typo.

File: src/components/invest/index.js [hunk 2]
```diff
@@ -116,26 +123,55 @@ export class Invest extends React.Component {
...
+    let timeInterval
+
+    if (crowdsalePageStore.ticks.length) {
+      nextTick = crowdsalePageStore.extractNextTick()
+      millisecondsToNextTic = nextTick.time - Date.now()
+
+      setTimeout(() => {
+        this.setState({ displaySeconds: true })
+      }, millisecondsToNextTic - 5*6e4)
```
Comment (fvictorio) [inline src/components/invest/index.js]: What does this do?

File: src/components/invest/index.js [hunk 3]
```diff
@@ -116,26 +123,55 @@ export class Invest extends React.Component {
...
+
+      timeInterval = setInterval(() => {
```
Comment (fvictorio) [inline src/components/invest/index.js]: Should we clear this in the `componentWillUnmount` hook?

File: src/stores/CrowdsalePageStore.js [hunk 4]
```diff
@@ -10,12 +10,52 @@ class CrowdsalePageStore {
...
-  @observable startBlock
-  @observable endDate;
+  @observable tiers = []
+  @observable ticks = []
 
   @action setProperty = (property, value) => {
     this[property] = value
   }
+
+  @action setTier = (tier) => {
```
Comment (fvictorio) [inline src/stores/CrowdsalePageStore.js]: The name of this method is misleading, it should be something like `addTier`, otherwise it seems idempotent.

File: src/components/invest/index.js (hunk 1 above)
Comment (fernandomg) [reply src/components/invest/index.js]: fixed

File: src/components/invest/index.js (hunk 2 above)
Comment (fernandomg) [reply src/components/invest/index.js]: sets the timeout to 5 minutes before the next tick. Anyway, I did refactored this part so it's clear.

```javascript
const FIVE_MINUTES_BEFORE_TICK = moment(millisecondsToNextTick).subtract(5, 'minutes').valueOf()

setTimeout(() => {
    this.setState({ displaySeconds: true })
}, FIVE_MINUTES_BEFORE_TICK)
```

File: src/components/invest/index.js (hunk 3 above)
Comment (fernandomg) [reply src/components/invest/index.js]: Done. I also did cleared the interval when the countdown finishes

File: src/stores/CrowdsalePageStore.js (hunk 4 above)
Comment (fernandomg) [reply src/stores/CrowdsalePageStore.js]: done, thanks!
