### PR TITLE
(Bug) Contribution page-Minimum Contribution field: incorrect text after crowdsale has been finalized

### LINKED ISSUE #1030: (Bug) Contribution page-Minimum Contribution field: incorrect text after crowdsale has been finalized
Steps:
1. Create crowdsale with any parameter, ex. :Minted, 1 tier, duration 2 min, minCap
2. Wait until crowdsale ended
3. As an owner open manage page and finalize
4. Open contribution page and observe field `Minimum Contribution`

Expected result:
-field `Minimum Contribution` should contain text "You are not allowed" or similar

Actual result:
-field `Minimum Contribution` contains text "infinity" 
- also incorrect validation message for contribution field

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*localhost*

### If you were able to create it, what is the URL of your crowdsale?

n/a

### Do you have screenshots showing the problem?

screen shot 2018-07-11 at 00 28 08

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

no

---

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #1030 

- Add validation when the number is not finite (Aka 'infinity')
- Fix some linting issues

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@mariano-aguero 
minContribution field should contain text "You are not allowed " if crowdsale has ended but not finalized
screen shot 2018-07-11 at 11 54 25

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Dutch: 
 - min contribution field still contains value instead text "You are not allowed"
 - button Contribute enabled after finalization

screen shot 2018-07-11 at 12 29 16

**Comment by mariano-aguero** [comment]
@dennis00010011b Added suggested behavior

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Dutch: min contribution field still contains value instead text "You are not allowed"  IF crowdsale was finalized before time was expired(all tokens were sold )

screen shot 2018-07-12 at 02 32 12

**Comment by mariano-aguero** [comment]
@dennis00010011b Before the last commit, it worked with respect to the finalization of the crowdsale (end time). Now add a validation regarding the finalization from the manage section.
Could you check it ?

**Comment by dennis00010011b** [comment]
@vbaranov 
Tested it .No issues were found

File: src/components/crowdsale/index.js [hunk 1]
```diff
@@ -17,7 +17,7 @@ import { NAVIGATION_STEPS } from '../../utils/constants'
 import { Loader } from '../Common/Loader'
 import { CrowdsaleConfig } from '../Common/config'
 import { inject, observer } from 'mobx-react'
-import { invalidCrowdsaleExecIDAlert, invalidCrowdsaleAddrAlert, invalidNetworkIDAlert } from '../../utils/alerts'
+import { invalidCrowdsaleExecIDAlert, invalidNetworkIDAlert } from '../../utils/alerts'
```
Comment (vbaranov) [inline src/components/crowdsale/index.js]: While `invalidNetworkIDAlert ` is not used somewhere in the code yet, but it should (related issue is https://github.com/poanetwork/token-wizard/issues/1044). I guess, we could leave it this line as is in this PR.

File: src/components/crowdsale/utils.js [hunk 2]
```diff
@@ -284,6 +284,16 @@ export const isFinalized = async ({ methods }, crowdsaleExecID) => {
   return is_finalized
 }
 
+export const isEnded = async ({ methods }, crowdsaleExecID) => {
```
Comment (vbaranov) [inline src/components/crowdsale/utils.js]: There is only end by time is checked here, but crowdsale can be ended also if it is full (hardcap is sold out). But I think it could be made in a separate PR.

File: src/components/contribute/ContributeForm.js [hunk 3]
```diff
@@ -12,24 +12,31 @@ import {
...
-        <a className={contributeButtonClasses} onClick={handleSubmit}>
+        <button className={contributeButtonClasses} onClick={handleSubmit} disabled={buttonDisabled}>
           Contribute
-        </a>
+        </button>
       ) : null
 
+    const canContribute = !(isEnded || isFinalized)
+
+    console.log(`Can contribute ${canContribute}`)
```
Comment (vbaranov) [inline src/components/contribute/ContributeForm.js]: @mariano-aguero `logger.log` ? (@fernandomg, I am logger 👮 today)

File: src/components/crowdsale/index.js (hunk 1 above)
Comment (mariano-aguero) [reply src/components/crowdsale/index.js]: Ok, It will remain that way

File: src/components/contribute/ContributeForm.js (hunk 3 above)
Comment (mariano-aguero) [reply src/components/contribute/ContributeForm.js]: I remove console.log

File: src/components/crowdsale/utils.js (hunk 2 above)
Comment (mariano-aguero) [reply src/components/crowdsale/utils.js]: Added function to check if a crowdsale is sold out, and validate the button

**Comment by mariano-aguero** [comment]
Probably fix issue #1029

**Comment by mariano-aguero** [comment]
I made the changes suggested by @fernandomg . Can you check is OK @vbaranov ? Fer is on vacations. Thanks in advance

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Dutch auction: countdown timer has status "Finalized " before start of crowdsale. As a result investors are not able to buy.
screen shot 2018-07-17 at 09 35 02

**Comment by mariano-aguero** [comment]
@dennis00010011b Good catch, The is_finalized property is not standardized in the contracts (same index for both), so I added a validation depending on the type of contract

File: src/components/crowdsale/utils.js [hunk 4]
```diff
@@ -274,14 +274,65 @@ let fillCrowdsalePageStoreDates = (startsAtMilliseconds, endsAtMilliseconds) =>
...
+  return end_time * 1000 <= Date.now()
+}
+
+/**
+ * Check if a crowdsale is sold out
+ * @param methods
+ * @param crowdsaleExecID
+ * @returns {Promise<*>}
+ */
+export const isSoldOut = async ({ methods }, crowdsaleExecID) => {
```
Comment (vbaranov) [inline src/components/crowdsale/utils.js]: Just to remind for future PR, that in frames of this comment https://github.com/poanetwork/token-wizard/issues/1026#issuecomment-403885893 this function should be redefined

File: src/components/crowdsale/utils.js [hunk 5]
```diff
@@ -274,14 +274,65 @@ let fillCrowdsalePageStoreDates = (startsAtMilliseconds, endsAtMilliseconds) =>
...
     params.push(addr, crowdsaleExecID)
   }
-  const { is_finalized } = await methods.getCrowdsaleInfo(...params).call()
-  return is_finalized
+  const crowdsale = await methods.getCrowdsaleInfo(...params).call()
+  const { isMintedCappedCrowdsale, isDutchAuction } = crowdsaleStore
+  let isFinalized = false
+  if (isMintedCappedCrowdsale) {
+    //Value is finalized is the index #3
+    isFinalized = crowdsale[3]
```
Comment (vbaranov) [inline src/components/crowdsale/utils.js]: Would you mind to keep track of the name of the property, if the returned item is an object:
`isFinalized = crowdsale.is_finalized || crowdsale[3]` ?

It will help us to be aware of the name of the property in smart-contracts

File: src/components/crowdsale/utils.js [hunk 6]
```diff
@@ -274,14 +274,65 @@ let fillCrowdsalePageStoreDates = (startsAtMilliseconds, endsAtMilliseconds) =>
...
+  } else if (isDutchAuction) {
+    //Value is finalized is the index #4
+    isFinalized = crowdsale[4]
```
Comment (vbaranov) [inline src/components/crowdsale/utils.js]: the same, as above ☝️

File: src/components/crowdsale/utils.js [hunk 7]
```diff
@@ -274,14 +274,65 @@ let fillCrowdsalePageStoreDates = (startsAtMilliseconds, endsAtMilliseconds) =>
...
+export const isEnded = async ({ methods }, crowdsaleExecID) => {
+  const { addr } = contractStore.abstractStorage
+  let params = []
+  if (crowdsaleExecID) {
+    params.push(addr, crowdsaleExecID)
+  }
+  const crowdsaleStartAndEndTimes = await methods.getCrowdsaleStartAndEndTimes(...params).call()
+  logger.log(`Crowdsale start time:`, crowdsaleStartAndEndTimes[0])
+  logger.log(`Crowdsale end time::`, crowdsaleStartAndEndTimes[1])
+  const end_time = crowdsaleStartAndEndTimes[1]
```
Comment (vbaranov) [inline src/components/crowdsale/utils.js]: the same, as above ☝️

File: src/components/crowdsale/utils.js [hunk 8]
```diff
@@ -274,14 +274,65 @@ let fillCrowdsalePageStoreDates = (startsAtMilliseconds, endsAtMilliseconds) =>
...
+ * @returns {Promise<*>}
+ */
+export const isSoldOut = async ({ methods }, crowdsaleExecID) => {
+  const { addr } = contractStore.abstractStorage
+  let params = []
+  if (crowdsaleExecID) {
+    params.push(addr, crowdsaleExecID)
+  }
+  const isCrowdsaleFull = await methods.isCrowdsaleFull(...params).call()
+  return isCrowdsaleFull && isCrowdsaleFull[0]
```
Comment (vbaranov) [inline src/components/crowdsale/utils.js]: Let's check the property's name if the returned item is an object or value at index if the returned item is an array. Would you mind?

Comment (mariano-aguero) [reply src/components/crowdsale/utils.js]: Of course :+1:  Done!

File: src/components/crowdsale/utils.js (hunk 7 above)
Comment (mariano-aguero) [reply src/components/crowdsale/utils.js]: Done!

File: src/components/crowdsale/utils.js (hunk 6 above)
Comment (mariano-aguero) [reply src/components/crowdsale/utils.js]: Done!

File: src/components/crowdsale/utils.js (hunk 5 above)
Comment (mariano-aguero) [reply src/components/crowdsale/utils.js]: Done!

File: src/components/crowdsale/utils.js (hunk 4 above)
Comment (vbaranov) [reply src/components/crowdsale/utils.js]: Yes, we could leave `isSoldOut` function as is and create an additional, for example, `tokensRemaining` function, that will check remaining tokens at the current tier. And add this new function there, where we check the possibility to finalize crowdsale.
